name: Deploy site ganeshin
#####pendiente: sacar las ramas y la sencuenciacion para el acumulado
on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master 
      - main
      - QA
      - onboarding
      - callcenter
      - regression
      - smoke
      - regresion

  pull_request:  
    branches: 
      - master 
      - main
      - QA
      - onboarding
      - callcenter
      - regression
      - smoke
      - regresion

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}     
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0
    - name: Generando static site
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build

    - name: Init new repo in dist folder and commit generated files
      run: |
        pwd
        ls -ll
        cd dist
        git init
        git add -A
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git commit -m 'deploy'
  ########################### Send Enviroments ##########################
    - name: Force push to destination branches to gh-pages
      uses: ad-m/github-push-action@master
      if: ${{ github.ref == 'refs/heads/master' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./dist
  ########################### Send path regresion ##########################    
    - name: Deploy to distinct directory
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/QA' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: regresion-tests
  ########################### Send path integracion ##########################       
    - name: Deploy to distinct directory
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/smoke' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: smoke-tests
  ########################### Send path Regression ##########################       
    - name: Deploy to distinct directory
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/regression' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: regression-tests      
  ########################### Send path callcenter ##########################       
    - name: Deploy to distinct directory
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/callcenter' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: callcenter-tests 
  ########################### Send path Onboarding ##########################       
    - name: Deploy to distinct directory
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/onboarding' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: onboarding-tests               